version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build app Docker image
          command: docker build -t app .
      - deploy:
          name: push app Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ] || [ "${CIRCLE_BRANCH}" == "release" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin
              docker tag app "${DOCKERHUB_USER}/ladder-web-server:${CIRCLE_BRANCH}"
              docker push "${DOCKERHUB_USER}/ladder-web-server:${CIRCLE_BRANCH}"
            fi
